image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli firebase-tools

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  only:
    - staging
  script:
    - firebase login:ci --token $FIREBASE_AUTH_TOKEN
    - firebase deploy --only hosting
  environment:
    name: production
    url: https://t-talk-23d6c.web.app/