name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                lfs: true
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.11'

            - name: Install dependencies
              run: npm install

            - name: Build project
              env:
                  API_KEY: ${{ secrets.API_KEY }}
                  APP_ID: ${{ secrets.APP_ID }}
                  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
                  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
                  PROJECT_ID: ${{ secrets.PROJECT_ID }}
                  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
              run: |
                npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.5.0
              with:
                  branch: gh-pages
                  folder: dist
