name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                lfs: true
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '20.11'

            - name: Install dependencies
              run: npm install

            - name: Create environment file
              run: |
                echo "export const environment = {" > environments/environment.ts
                echo "  apiKey: '${{ secrets.API_KEY }}'," >> environments/environment.ts
                echo "  authDomain: '${{ secrets.AUTH_DOMAIN }}'," >> environments/environment.ts
                echo "  projectId: '${{ secrets.PROJECT_ID }}'," >> environments/environment.ts
                echo "  storageBucket: '${{ secrets.STORAGE_BUCKET }}'," >> environments/environment.ts
                echo "  messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}'," >> environments/environment.ts
                echo "  appId: '${{ secrets.APP_ID }}'" >> environments/environment.ts
                echo "};" >> environments/environment.ts

            - name: Build project
              run: |
                npm run build
                mv dist/t-talk/browser/* dist/t-talk

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.5.0
              with:
                  branch: gh-pages
                  folder: dist
